name: dotto_design_system

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  widgetbook: 3.3.0
  widgetbook_annotation: 3.9.0

dev_dependencies:
  build_runner: 2.10.5
  very_good_analysis: 10.0.0
  widgetbook_generator: 3.20.1

flutter:
  uses-material-design: true
