name: dotto_design_system

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook:
  widgetbook_annotation:

dev_dependencies:
  build_runner:
  very_good_analysis:
  widgetbook_generator:

flutter:
  assets:
    - assets/
  fonts:
    - family: MPLUS1p
      fonts:
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_1p/static/MPLUS1p-Black.ttf
          weight: 900
  uses-material-design: true
