name: dotto_design_system

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook:
  widgetbook_annotation:

dev_dependencies:
  build_runner:
  very_good_analysis:
  widgetbook_generator:

flutter:
  uses-material-design: true
