name: dotto
description: For FUN Students
publish_to: "none"

version: 1.6.0+0

environment:
  sdk: ^3.10.8

dependencies:
  app_links: 7.0.0
  carousel_slider: 5.1.2
  cloud_firestore: 6.1.2
  collection: 1.19.1
  cupertino_icons: 1.0.8
  dio: 5.9.1
  dotto_design_system:
    path: ./dotto_design_system
  firebase_analytics: 12.1.1
  firebase_app_check: 0.4.1+4
  firebase_auth: 6.1.4
  firebase_core: 4.4.0
  firebase_crashlytics: 5.0.7
  firebase_database: 12.1.2
  firebase_messaging: 16.1.1
  firebase_remote_config: 6.1.4
  firebase_storage: 13.0.6
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: 2.2.0
  flutter_local_notifications: 20.0.0
  flutter_localizations:
    sdk: flutter
  flutter_overboard: 3.1.3
  flutter_pdfview: 1.4.4
  flutter_rating_bar: 4.0.1
  flutter_riverpod: 3.1.0
  flutter_slidable: 4.0.3
  flutter_staggered_grid_view: 0.7.0
  flutter_svg: 2.2.3
  freezed_annotation: 3.1.0
  geolocator: 14.0.2
  google_sign_in: 7.2.0
  http: 1.6.0
  intl: 0.20.2
  json_annotation: 4.9.0
  minio: 3.5.8
  openapi:
    path: ./api
  package_info_plus: 9.0.0
  path: 1.9.1
  path_provider: 2.1.5
  riverpod_annotation: 4.0.0
  settings_ui: 2.0.2
  share_plus: 12.0.1
  shared_preferences: 2.5.4
  shimmer_animation: 2.2.2+1
  sqflite: 2.4.2
  timezone: 0.10.1
  url_launcher: 6.3.2

dev_dependencies:
  build_runner: 2.11.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_native_splash: 2.4.7
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  json_serializable: 6.11.2
  mockito: 5.6.3
  riverpod_generator: 4.0.0+1
  very_good_analysis: 10.1.0

flutter:
  assets:
    - assets/
    - assets/map/
    - assets/tutorial/
  config:
    enable-swift-package-manager: true
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  web: false
  image_path: "assets/icon1024x1024.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon768x768.png"
