name: dotto
description: For FUN Students
publish_to: "none"

version: 1.6.0+0

environment:
  sdk: ^3.10.0

dependencies:
  app_links:
  carousel_slider:
  cloud_firestore:
  collection:
  cupertino_icons:
  dio:
  dotto_design_system:
    path: ./dotto_design_system
  firebase_analytics:
  firebase_app_check:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_database:
  firebase_messaging:
  firebase_remote_config:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus:
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  flutter_overboard:
  flutter_pdfview:
  flutter_rating_bar:
  flutter_riverpod:
  flutter_slidable:
  flutter_staggered_grid_view:
  flutter_svg:
  freezed_annotation:
  geolocator:
  google_sign_in:
  http:
  intl:
  json_annotation:
  minio:
  openapi:
    path: ./api
  package_info_plus:
  path:
  path_provider:
  riverpod_annotation:
  settings_ui:
  share_plus:
  shared_preferences:
  shimmer_animation:
  sqflite:
  timezone:
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  mockito:
  riverpod_generator:
  very_good_analysis:

flutter:
  assets:
    - assets/
    - assets/map/
    - assets/tutorial/
  config:
    enable-swift-package-manager: true
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  web: false
  image_path: "assets/icon1024x1024.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon768x768.png"
