name: openapi
version: 1.0.0
description: Dotto API client

environment:
  sdk: ^3.10.8

dependencies:
  dio: 5.9.1
  one_of: 1.5.0
  one_of_serializer: 1.5.0
  built_value: 8.12.3
  built_collection: 5.1.1

dev_dependencies:
  built_value_generator: 8.12.3
  build_runner: 2.10.5
  test: 1.29.0
